### ISSUE TITLE
read depth incorrect

### ISSUE THREAD

**Issue by bioscienceresearch** [genome/bam-readcount#103]
I am using bam-readcount with the following command:

`bam-readcount -w1 -f NC_045512_2.fa aligned_data.bam NC_045512.2:1-29903`

Also:

`bam-readcount -w1 -f NC_045512_2.fa aligned_data.bam NC_045512.2:8782-8782`

The output read counts from bam-readcount (eg 5-12) is two to three orders of magnitude lower than number of reads mapping to specific locations (c. 2000 to 8782). Tested on multiple bam files.

For bam files with low read coverage, the counts are correct.

version: 1.0.1-unstable-8-c7c76e6 (commit c7c76e6)

**Comment by bioscienceresearch** [comment]
I found the issue, due to Marking reads as PCR duplicates (1024/1040 FLAG). have taking out duplicate marking step. Bam-readcount giving correct depth.

**Comment by chrisamiller** [comment]
Glad you figured it out!
