### ISSUE TITLE
conda version different than github

### ISSUE THREAD

**Issue by complexgenome** [genome/bam-readcount#106]
Hi there developers,
I'm interested to install bam-readcount from conda. It seems the version there hasn't been updated. It's 0.8, whereas, on github it's 1.0.1

Do you plan to update conda version?

https://anaconda.org/bioconda/bam-readcount

**Comment by chrisamiller** [comment]
We don't currently have plans to push to conda, but wouldn't object if someone else wants to take the initiative.  Best of luck!
