### ISSUE TITLE
segmentation faults on OSX 10.9.2 with Samtools 0.1.19-44428cd

### ISSUE THREAD

**Issue by lordzappo** [genome/bam-readcount#12]
Hi-  This doesn't seem to work correctly.  These are Illumina Platinum Genome bams downloaded from Basespace that work with samtools mpileup:

**samtools mpileup NA12888_S1.bam -r chr1:10291-10291**

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
chr1	10291	N	50	tT$c$TTTcttccc-1ncTt$gcgccccccTCC+1TccCCtccgccccccCcccccc^8c^>C	@8B?8<BG=HGCDG@A;BDB8B50GGGB5IE895899;505D2<20070@

*counting position 10005-10005 works:*

**bam-readcount -f hg19.fa NA12888_S1.bam  chr1:10005-10005**
Minimum mapping quality is set to 0
chr1	10005	c	265	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:265:7.65:34.62:4.98:258:7:0.06:0.02:24.99:258:0.95:95.32:0.8G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

*~300bp away seg faults*

**bam-readcount -f hg19.fa NA12888_S1.bam  chr1:10291-10291**
Minimum mapping quality is set to 0
Segmentation fault: 11

Ideas?

**Comment by ernfrid** [comment]
Working well for me now. I am closing.
