### ISSUE TITLE
bam-readcount does not install on centos 5

### ISSUE THREAD

**Issue by dnjiao** [genome/bam-readcount#15]
I am trying to compile bam-readcount on this centos 5 system using cmake 3.0.2. "cmake" and "make deps" all went through. However "make" failed with the following errors:

Linking CXX executable ../../../../bin/bam-readcount
../../../../vendor/boost/lib/libboost_program_options.a(options_description.o): In function `boost::program_options::options_description::print(std::basic_ostream<char, std::char_traits<char> >&) const':
options_description.cpp:(.text+0x2a8b): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
options_description.cpp:(.text+0x2aa8): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
options_description.cpp:(.text+0x2abf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
options_description.cpp:(.text+0x2ad3): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
options_description.cpp:(.text+0x2d03): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
../../../../vendor/boost/lib/libboost_program_options.a(options_description.o):options_description.cpp:(.text+0x2fc4): more undefined references to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)' follow
collect2: ld returned 1 exit status
make[2]: *** [bin/bam-readcount] Error 1
make[1]: *** [build/src/exe/bam-readcount/CMakeFiles/bam-readcount.dir/all] Error 2
make: *** [all] Error 2

As it seems to be the issue of Boost, I tried to link Boost 1.55 which is installed system wide by adding the following lines to CMakeLists.txt and remove boost-1.55 from dependencies.

set(BOOST_INCLUDE "/risapps/rhel5/boost/1.55.0/include")
find_package(Boost REQUIRED)
include_directories(${BOOST_INCLUDE})

It failed at "cmake" again saying "include could not find load file: /usr/lib64/boost/Boost.cmake". 

Please advise.

**Comment by HungerNature** [comment]
change g++ complier might works well. 
similar issue in Biostar here: https://www.biostars.org/p/197804/
