### ISSUE TITLE
Many single-end mapping quality warnings

### ISSUE THREAD

**Issue by sjackman** [genome/bam-readcount#2]
BWA-MEM 0.7.4 does not output single-end mapping qualities. Running bam-readcount results in millions (one per read) of warnings. Please emit one warning and suppress all following warnings.

```
Couldn't grab single-end mapping quality for read M01171:3:000000000-A3E2L:1:1101:10683:2958. Check to see if SM tag is in BAM
```

**Comment by fpbarthel** [comment]
Hi, I have the impression that  it does affect the fpfilter.pl results. Whenever this error appears, I consistently have fpfilter returning nothing, eg:

15988 variants in input file
15988 had a bam-readcount result
15964 had reads1>=2
0 passed filters
15988 failed filters
        0 failed because no readcounts were returned
        0 failed minimim variant count < 2
        143 failed minimum variant freq < 0.1
        3494 failed minimum strandedness < 0.1
        48 failed minimum variant readpos < 0.1
        96 failed minimum variant dist3 < 0.1
        6610 failed maximum variant MMQS > 150
        5029 failed maximum MMQS diff (var - ref) > 150
        143 failed maximum mapqual diff (ref - var) > 50
        2658 failed minimim ref mapqual < 30
        9454 failed minimim var mapqual < 30
        15976 failed minimim ref basequal < 30
        15919 failed minimim var basequal < 30
        1342 failed maximum RL diff (ref - var) > 0.25

**Comment by ernfrid** [comment]
The number failing the minimum basequality filter is _very_ surprising to me. It seems to me it could be one of two things:

1. A parsing error in the fpfilter.pl script
2. Much lower basequalities than I'm used to seeing on Illumina data.

Where did you fpfilter.pl come from? Has it been modified?

Would you be able to share an example line from your data? I don't need the position information, just the count section.

**Comment by fpbarthel** [comment]
I wonder if it's the first one. This is Broad aligned Illumina WGS seq data which I guess passed rigorous QC.

The fpfilter I'm using is the VarScan version which has been integrated in the latest release 2.3.9 here https://sourceforge.net/projects/varscan/files/. It's not been modified in any way.

See also my thread there https://sourceforge.net/p/varscan/discussion/1073559/thread/b2c0c9cb/.

Here's the first few lines of an example input file https://dl.dropboxusercontent.com/u/2003036/test2.snp.Somatic.hc (~9kb)
And readcount file https://dl.dropboxusercontent.com/u/2003036/test2.snp.Somatic.hc.rc (~34kb)

**Comment by ernfrid** [comment]
I think there might be an off by one error in the bam-readcount parsing parts of the integrated fpfilter. I would suggest moving back to using the perl script instead. Dan is out of the office until next week, but may be able to address the issue when he returns.

**Comment by ernfrid** [comment]
On further review, I take that back. I misread the code. I think the issue here is that for your data the avg basequality is actually a little less than 30. Base quality recalibration usually lower base qualities so the default of 30 here is likely to be too high on these data. I would consider reducing the cutoff there and seeing if that fixes the issue.

**Comment by fpbarthel** [comment]
Somehow suprising because the data that has this is very new data, sequenced late last year/early this year whereas the data that does not is much older (several years). All of it is Broad data. There is one thing different, that is that the read length is 150bp versus 101 bp on the older data.

**Comment by ernfrid** [comment]
It depends on the platform. I believe the HiSeq X does have lower base qualities than older Illumina platforms (although I do not know if these data were generated on that platform). At MGI, we do not filter on average base quality (this appears to be a recent addition to VarScan) and I do not have a good sense for appropriate cutoffs. If you are still observing issues with the perl script, I am happy to troubleshoot, but unfortunately, further investigation into the newly integrated VarScan filter would need to wait until Dan is back.

**Comment by fpbarthel** [comment]
I think you're right that these might be too stringent. I work with glioma data and these filters seem to have removed all IDH mutations and all TERT promoter mutations.It's quite surprising that there are still 400k mutations left!

**Comment by ernfrid** [comment]
Well that seems like a good positive control and those results are not reassuring. I would be curious to know if using the Perl script helps.

**Comment by fpbarthel** [comment]
I followed your initial suggestion and changed the minimum base quality (variant and reference) to 10. This was able to recover all TERT and IDH mutatations (over 70 collectively) which suggests that this filter was the major culprit. Results look good so far.

**Comment by ernfrid** [comment]
Ah, excellent. I will relay to Dan.
