### ISSUE TITLE
Parallel make fails

### ISSUE THREAD

**Issue by sjackman** [genome/bam-readcount#22]
`make -j4` fails. `make -j1` builds fine.
```
❯❯❯ make -j4
…
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/bam-readcount20150612-1951-1wqpaid/bam-readcount-0.7.4/build/CMakeFiles  3 4 5 6 7 8 9 10
[100%] Built target boost-1.55
make: *** [all] Error 2
```

**Comment by ernfrid** [comment]
Oops.

**Comment by ernfrid** [comment]
This is a known issue with the dependencies. Currently you need to do: `make -j deps` followed by `make -j install`. I'm going to leave this open because a little bird told me they'd figured out how to make this work more elegantly and I would like to potentially fix it.

**Comment by sjackman** [comment]
Thanks for the workaround, Dave.

**Comment by ernfrid** [comment]
The two stage build process should no longer be necessary. Please do let us know if you run into any troubles though.
