### ISSUE TITLE
Maximum depth defaults to 8000

### ISSUE THREAD

**Issue by sjackman** [genome/bam-readcount#3]
The maximum depth appears to default to 8000, which is, I believe, behaviour inherited from samtools:
https://github.com/samtools/samtools/blob/master/bam_plcmd.c#L322

Please add an option `-d` similar to `samtools mpileup` to allow changing this default:

> -d INT       max per-BAM depth to avoid excessive memory usage

https://github.com/samtools/samtools/blob/master/bam_plcmd.c#L566

Thanks,
Shaun

**Comment by VivekTodur** [comment]
Hi,

I am using bam-readcount (0.7.4) ,  as part of varscan somatic pipeline, but while applying fpfilter, getting error like this,

740 variants in input file
0 had a bam-readcount result
0 had reads1>=2
0 passed filters
740 failed filters
	740 failed because no readcounts were returned
	0 failed minimim variant count < 3
	0 failed minimum variant freq < 0.05
	0 failed minimum strandedness < 0.0
	0 failed minimum reference readpos < 0.2
	0 failed minimum variant readpos < 0.15
	0 failed minimum reference dist3 < 0.2
	0 failed minimum variant dist3 < 0.15
	0 failed maximum reference MMQS > 50
	0 failed maximum variant MMQS > 100
	0 failed maximum MMQS diff (var - ref) > 50
	0 failed maximum mapqual diff (ref - var) > 10
	0 failed minimim ref mapqual < 20
	0 failed minimim var mapqual < 30
	0 failed minimim ref basequal < 15
	0 failed minimim var basequal < 30
	0 failed maximum RL diff (ref - var) > 0.05

I am not able to figure out, what could be the reason for this...

Thanks,
Vt,

**Comment by xiezhan** [comment]
Hi Shaun:
   I met a question exactly same with yours when I used bam-readcount recently.But when I add _-d_ ,bam-readcount still can't give me right answer.In other words,_-d_ change nothing.
  Would u give me some advices?
  Thanks so much!
 
Wishes;
 Zhan

**Comment by sjackman** [comment]
Which version of `bam-readcount` are you using?

**Comment by xiezhan** [comment]
bam-readcount-0.7.4
Could u tell me yours?

**Comment by sjackman** [comment]
Same. The most recent is 0.7.4

**Comment by xiezhan** [comment]
Did u meet the same question？

**Comment by sjackman** [comment]
I did back in 2013, but the problem was fixed for me. I haven't tested it again recently.

**Comment by jcomand** [comment]
Hi, it appears to be broken again. (version: 0.8.0-unstable-5-1b9c52c commit 1b9c52c)

The -d option does nothing. I saw a reference to "--max-count" as well as "--count" in error messages- is the param being passed to pileup correctly?

I gave it 100 reads in the same location and it returns 100 depth.  But if I give it 10,000 or more reads, it gives 8018 depth.  The -d has no effect.

$ bam-readcount 100readsat1000bp.fastq.bam.sorted.bam 2> /dev/null | grep 1000
rhoplasmid      1000    N       **100**     =:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  C:100:60.00:36.94:60.00:100:0:0.00:0.00:0.00:0:0.00:0.00:0.00   G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00       T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
$ bam-readcount 10000readsat1000bp.fastq.bam.sorted.bam 2> /dev/null | grep 1000
rhoplasmid      1000    N       **8018**    =:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  C:8018:60.00:36.57:60.00:8018:0:0.00:0.00:0.00:0:0.00:0.00:0.00 G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00       T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

$ bam-readcount -d **1000000** 10000readsat1000bp.fastq.bam.sorted.bam 2> /dev/null | grep 1000
rhoplasmid      1000    N       **8018**    =:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  C:8018:60.00:36.57:60.00:8018:0:0.00:0.00:0.00:0:0.00:0.00:0.00 G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00       T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

$bam-readcount -d **10** 10000readsat1000bp.fastq.bam.sorted.bam 2> /dev/null | grep 1000
rhoplasmid      1000    N       **8018**    =:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  C:8018:60.00:36.57:60.00:8018:0:0.00:0.00:0.00:0:0.00:0.00:0.00 G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00       T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

FYI error file contains:
Minimum mapping quality is set to 0
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
WARNING: In read M03309:128:000000000-ARE9N:1:2110:18089:28088: Couldn't find the generated tag.
...

I don't think the errors are related, not sure.

Thank you very much.

**Comment by jcomand** [comment]
See issue #19 , duplicate
workaround is specify reference and region.  the -d flag works and the default is higher.

$ bam-readcount **-f ~/rho_reference/rhoplasmid.fa** **44475**readsat1000bp.fastq.bam.sorted.bam **rhoplasmid:1000-1000**
Minimum mapping quality is set to 0
rhoplasmid      1000    C       **44472**   =:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  C:44472:60.00:36.49:60.00:44471:1:0.59:0.00:10.32:44471:0.49:120.40:0.49        G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00       T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00  N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by snuernberg** [comment]
I'm having the same problem with version 0.8:

 ~/bam-readcount/build/bin/bam-readcount -q 30 -d 10000000 ~/IgG_RbpjChIP_chr7.bam > IgG_Rbpj_chr7_maxcount10mil.txt

hr7	19049345	N	**8017**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:8013:59.98:35.94:59.98:8013:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	T:3:60.00:36.00:60.00:3:0:0.00:0.03:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049346	N	**8019**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:2:60.00:36.00:60.00:2:0:0.00:0.02:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:8015:59.98:35.92:59.98:8015:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:2:60.00:36.00:60.00:2:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049347	N	**8020**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:8018:59.98:35.92:59.98:8018:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:1:60.00:14.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	T:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049348	N	**8021**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:8020:59.98:35.94:59.98:8020:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:1:60.00:14.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049349	N	**8022**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:8020:59.98:35.91:59.98:8020:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:2:60.00:36.00:60.00:2:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049350	N	**8023**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	G:8007:59.98:35.90:59.98:8007:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:15:59.40:34.53:59.40:15:0:0.00:0.03:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049351	N	**8024**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:8020:59.98:35.97:59.98:8020:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:3:60.00:36.00:60.00:3:0:0.00:0.02:0.00:0:0.00:0.00:0.00	T:1:60.00:14.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049352	N	**8025**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	C:1:54.00:36.00:54.00:1:0:0.00:0.04:0.00:0:0.00:0.00:0.00	G:1:60.00:14.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	T:8022:59.98:35.94:59.98:8022:0:0.00:0.00:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049353	N	**8025**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:8016:59.98:35.84:59.98:8016:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:8:60.00:36.00:60.00:8:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049354	N	**8026**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:8026:59.98:35.92:59.98:8026:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049355	N	**8028**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:2:60.00:25.00:60.00:2:0:0.00:0.02:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:8013:59.98:35.83:59.98:8013:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:13:59.54:35.69:59.54:13:0:0.00:0.02:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
chr7	19049356	N	**8029**	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:1:60.00:36.00:60.00:1:0:0.00:0.02:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:8012:59.98:35.85:59.98:8012:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:16:58.88:36.00:58.88:16:0:0.00:0.03:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00

According to bamCoverage this region is covered by millions of reads.

Is there a fix for this?

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by ernfrid** [comment]
There is no fix. The workaround remains to specify regions from the command line. If you need entire chromosomes then specifying the entire chromosome with no coordinates should work for the command line interface.

**Comment by snuernberg** [comment]
Unfortunately specifying regions leads to segfaults :/

**Comment by ernfrid** [comment]
try ensuring you provide a reference sequence and see if that fixes it
