### ISSUE TITLE
Compilation error with abs function in BasicStat.cpp

### ISSUE THREAD

**Issue by germelcar** [genome/bam-readcount#32]
I just compile your tool in a GNU/Linux distro, using GCC 6.1.1 20160802, but there is a problem with the "BasicStat.cpp" file, specifically, with the "abs" function used at the line 70. The error was:

> BasicStat.cpp:69:86: error: call of overloaded ‘abs(float)’ is ambiguous
>          sum_event_location += 1.0 - abs((float)(base->qpos - left_clip) - read_center)/read_center;

I don't knwo if it is the right way but I have solved it including "cmat" header and changing from "abs" to "fabs".

Hope that helps.

**Comment by ernfrid** [comment]
Thanks for pointing this out. I was unable to reproduce in a Ubuntu16.04 using gcc-6. Regardless, I've updated to including `cmath` and switching to `std::abs` which I think should make this go away based on what you've said. Let me know if that doesn't do the trick for you.
