### ISSUE TITLE
CIGAR error

### ISSUE THREAD

**Issue by avilella** [genome/bam-readcount#39]
I am receiving errors from using readcount on a bam file aligned with bwa mem:

```
2017-03-31 11:26:05 bam_readcount STDERR ERROR (CigarRoller.cpp:127): Parsing CIGAR - invalid character found with parameter * and 0
```

Any ideas what may be wrong?

**Comment by ernfrid** [comment]
I think you may have the wrong Github repo to post this issue. There's no CigarRoller.cpp in this bam-readcount. There is another program called bam-readcount that is part of libStatGen (https://github.com/statgen/libStatGen) that does appear to have this file. You may have better luck there.
