### ISSUE TITLE
Filteriing paired end data

### ISSUE THREAD

**Issue by runnerBio88** [genome/bam-readcount#45]
Hi

I'm using bamreadcount output as input for pVACseq.
The thing is that I'm using paired end data from DNA and RNA, and I warnings like: 

> WARNING: In read XXXXXXXXXXXXXXXXXX: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
I'm filtering using the parameter -b 20. 

I'm not sure how this is affecting the filtering. I'm guessing the filtering by quality position is not being affected by this.
But, What would happen if I was filtering instead by -b but by -q?

Thanks for your time.

**Comment by ernfrid** [comment]
It won't affect filtering at all. It will only affect the calculation of the avg_se_mapping_quality field.

**Comment by runnerBio88** [comment]
Thanks for this fast answer!
