### ISSUE TITLE
read count limit 8000

### ISSUE THREAD

**Issue by snuernberg** [genome/bam-readcount#51]
Is there a workaround changing the read count limit?
-d doesn't work (at least without specifying a region - which I can't do as this leads to segfaults)

 ~/bam-readcount/build/bin/bam-readcount -q 30 -d 10000000 ~/IgG_RbpjChIP_chr7.bam > IgG_Rbpj_chr7_maxcount10mil.txt

chr7	19049388	N	7997	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:7052:60.00:35.90:60.00:79:6973:0.00:0.02:0.00:0:0.00:0.00:0.00	C:2:60.00:36.00:60.00:0:2:0.00:0.02:0.00:0:0.00:0.00:0.00	G:939:59.96:35.81:59.96:12:927:0.00:0.00:0.00:0:0.00:0.00:0.00	T:3:60.00:21.33:60.00:0:3:0.00:0.03:0.00:0:0.00:0.00:0.00	N:1:60.00:2.00:60.00:0:1:0.00:0.08:0.00:0:0.00:0.00:0.00

According to bamCoverage this region is covered by 6 million reads...

**Comment by Dave217** [comment]
You may have resolved this on your own, but for future internet searchers, the resolution to this is that you have to specify a region, even if the region is the whole reference sequence.

**Comment by DepledgeLab** [comment]
This is a useful piece of information that just helped me resolve a significant issue I was having. Out of interest, when specifying a -d value below the maximum read depth, how does bamreadcount decide which reads to keep/discard? Is this random or simply based on left-mode co-ordinate?

**Comment by chrisamiller** [comment]
It just grabs the first N reads.  (see comment from HTSlib contributor here:  https://github.com/samtools/bcftools/issues/635)
