### ISSUE TITLE
a question of how to use bam-readcount on insertions?

### ISSUE THREAD

**Issue by rayliu0115** [genome/bam-readcount#57]
Hi there,

I am doing a test about the function of VarScan (v2.4.3) fpfilter, but I am confused how to make the readcount region for insertions. For SNVs, the regions look like "chr pos pos", and the regions of deletions should be "chr pos+1 pos+1". So, should I also make the insertion region like "chr pos+1 pos+1" and run bam-readcout with -i ?

Thanks so much and wait for your reply

Rui

**Comment by sbamin** [comment]
I find getting readcounts on indels less reliable using bam-readcount but still uses it for filtering varscan2 calls<sup>[Koboldt 2013](https://www.ncbi.nlm.nih.gov/pubmed/25553206)</sup>. See #54 and https://github.com/bedops/bedops/issues/11 for related discussions.

For now, for each vcf with snv and indel calls, I generate following three files using `vcf2bed` from BEDOPS tools. These are 0-based BED, so need to add +1 to start coordinate

```sh
vcf2bed --snv < myVariants.vcf > mySnvs.bed
vcf2bed --insertion < myVariants.vcf > myInsertions.bed
vcf2bed --deletion < myVariants.vcf > myDeletions.bed
```
