### ISSUE TITLE
Max depth 8000

### ISSUE THREAD

**Issue by LauraVP1994** [genome/bam-readcount#69]
Dear,

Althought this would be a great tool, I encountered quite a big problem for my data with bam-read-count. Just like samtools depth it seems not to deal well with high coverages. I have coverages ranging from 5000-90 000X and bamreadcount seems to limit itself to 8000. I found a few posts that tried to deal with this with the -d option. However this doesn't seem to work. 

Maybe an update or a clear workaround is necessary for people that work with high coverages like viral data.

Kind regards
Laura

**Comment by cjfields** [comment]
I was able to get this to work as follows up to 10,000,000x depth (I think the default).  This may require both the reference FASTA _and_ the segment at the end.

```
# filter bases at 
bam-readcount -b 30 -w 1 -f $REFERENCE my.sorted.bam chrID
```
