### ISSUE TITLE
Compilation fails because of missing -fPIC

### ISSUE THREAD

**Issue by SethosII** [genome/bam-readcount#75]
I tried to build the new release but it fails. It succeeds with `-fPIC`:

```
$ mkdir build
$ cd build
$ cmake ..
$ make -j
...
/dev/shm/bam-readcount-1.0.0/build/vendor/mbedtls/lib/libmbedcrypto.a(poly1305.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
$ make clean
$ export CFLAGS="-fPIC"
$ make -j
```

**Comment by apldx** [comment]
Can you provide more platform information? We'd like to keep a record of build issues.

**Comment by SethosII** [comment]
@apldx I used Ubuntu 20.04 with the [GCC 10.3.0 toolchain](https://github.com/easybuilders/easybuild-easyconfigs/blob/main/easybuild/easyconfigs/g/GCC/GCC-10.3.0.eb) from [EasyBuild](https://easybuild.io/). 

I did more testing and it works with the packages from the Ubuntu repositories. It seems to be related to their binutils version ([binutils/2.36.1-GCCcore-10.3.0](https://github.com/easybuilders/easybuild-easyconfigs/blob/main/easybuild/easyconfigs/b/binutils/binutils-2.36.1-GCCcore-10.3.0.eb)). Building works without it so it seems to be an issue there.
