### ISSUE TITLE
[JOSS REVIEW] minor edits to the manuscript

### ISSUE THREAD

**Issue by friedue** [genome/bam-readcount#82]
Related to: <https://github.com/openjournals/joss-reviews/issues/3722>

- [x] please extend the "statement of need" a bit, or rephrase it so that within the first sentence it is already obvious that `bam-readcount` is not so much just about counting reads, but primarily about collecting metrics that are particularly helpful in judging wether a specific variant call is reliable or not (or maybe that's not even the primary use-case, who knows! :) )
- [x] similarly, the conclusion should state a bit more clearly what precisely the role of `bam-readcount` is in the bespoke pipelines and the use cases that are mentioned there
- [x] lines 37 and 54 should have "its" instead of "it's"

**Comment by friedue** [comment]
Great update to the text! The use-cases of the tool are very clearly described now, great job!

[ ] There's a typo on line 61, and there might be a letter missing in line 50, too ("disks?").

**Comment by chrisamiller** [comment]
Thanks - fixed and pushed!
