### ISSUE TITLE
[JOSS REVIEW] Any functionality documentation?

### ISSUE THREAD

**Issue by bebatut** [genome/bam-readcount#84]
Related to https://github.com/openjournals/joss-reviews/issues/3722:

> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Is there any functionality documentation? If there is, where can we find it? I could not find anything at first sight

**Comment by apldx** [comment]
Though the code is divided into a front-end and library, we don't aim to expose the library code as an API. For the command-line program `bam-readcount`, the intro section of the `README.md` hopefully indicates what it does, and then the actual usage is documented under `Usage`. The output is complicated and so has its own section `Output`. Do you have thoughts on what more might be needed? Thanks!

**Comment by bebatut** [comment]
Looks good
